# Generated by Django 4.1 on 2023-06-27 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("city_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("country_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("state_name", models.CharField(max_length=50, unique=True)),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Profiles.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="School_Profiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("school_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("number", models.CharField(max_length=15)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("address", models.CharField(max_length=400)),
                (
                    "city_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_profiles",
                        to="Profiles.city",
                    ),
                ),
                (
                    "country_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_profiles",
                        to="Profiles.country",
                    ),
                ),
                (
                    "state_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_profiles",
                        to="Profiles.state",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Profiles",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Profiles.country"
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="state_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Profiles.state"
            ),
        ),
    ]
