# Generated by Django 4.1 on 2023-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school_profiles",
            name="cover",
            field=models.ImageField(blank=True, upload_to="school_covers"),
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="logo",
            field=models.ImageField(blank=True, upload_to="school_logos"),
        ),
    ]
