# Generated by Django 4.1 on 2023-07-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0002_school_profiles_cover_school_profiles_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school_profiles",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="static\\images\\school_default_2.png",
                upload_to="school_logos",
            ),
        ),
    ]
