# Generated by Django 4.1 on 2023-07-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0003_alter_school_profiles_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school_profiles",
            name="cover",
            field=models.ImageField(
                default="static\\images\\school_default_cover1.jpg",
                upload_to="school_covers",
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="logo",
            field=models.ImageField(
                default="static\\images\\school_default_2.png", upload_to="school_logos"
            ),
        ),
    ]
