# Generated by Django 4.1 on 2023-07-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0005_classespresent_schoolboard_schoolformat_schooltype"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(blank=True)),
                ("class_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "School Class",
            },
        ),
        migrations.DeleteModel(
            name="ClassesPresent",
        ),
        migrations.AlterModelOptions(
            name="schoolboard",
            options={"verbose_name_plural": "School Board"},
        ),
        migrations.AlterModelOptions(
            name="schoolformat",
            options={"verbose_name_plural": "School Format"},
        ),
        migrations.AlterModelOptions(
            name="schooltype",
            options={"verbose_name_plural": "School Type"},
        ),
    ]
