# Generated by Django 4.1 on 2023-07-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0007_rename_class_name_schoolclass_school_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="school_profiles",
            name="about",
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
