# Generated by Django 4.1 on 2023-07-05 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0008_school_profiles_about"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school_profiles",
            old_name="city_id",
            new_name="city",
        ),
        migrations.RenameField(
            model_name="school_profiles",
            old_name="country_id",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="school_profiles",
            old_name="state_id",
            new_name="state",
        ),
    ]
