# Generated by Django 4.1 on 2023-07-06 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0009_rename_city_id_school_profiles_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school_profiles",
            name="school_board",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.schoolboard",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="school_class",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.schoolclass",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="school_format",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.schoolformat",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="school_type",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.schooltype",
            ),
            preserve_default=False,
        ),
    ]
