# Generated by Django 4.1 on 2023-07-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0010_school_profiles_school_board_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolclass",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schoolformat",
            name="school_format",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="schooltype",
            name="school_type",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
