# Generated by Django 4.1 on 2023-07-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0012_remove_school_profiles_school_class_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schoolboard",
            options={
                "ordering": ["school_board"],
                "verbose_name_plural": "School Board",
            },
        ),
        migrations.AlterModelOptions(
            name="schoolclass",
            options={"ordering": ["rank"], "verbose_name_plural": "School Class"},
        ),
        migrations.RemoveField(
            model_name="school_profiles",
            name="school_board",
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="school_board",
            field=models.ManyToManyField(blank=True, to="Profiles.schoolboard"),
        ),
    ]
