# Generated by Django 4.1 on 2023-07-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "Profiles",
            "0013_alter_schoolboard_options_alter_schoolclass_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="school_profiles",
            name="coed_status",
            field=models.CharField(
                choices=[
                    ("option1", "Co-ed"),
                    ("option2", "Boys"),
                    ("option3", "Girls"),
                ],
                default="Co-ed",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="ownership",
            field=models.CharField(
                choices=[("option1", "Private"), ("option2", "Government")],
                default="Private",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="school_medium",
            field=models.CharField(
                choices=[
                    ("option1", "English"),
                    ("option2", "Bengali"),
                    ("option3", "Hindi"),
                ],
                default="English",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="school_timings",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
