# Generated by Django 4.1 on 2023-07-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0015_school_profiles_year_established_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school_profiles",
            name="coed_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("option1", "Co-ed"),
                    ("option2", "Boys"),
                    ("option3", "Girls"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="ownership",
            field=models.CharField(
                blank=True,
                choices=[("option1", "Private"), ("option2", "Government")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="school_medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("option1", "English"),
                    ("option2", "Bengali"),
                    ("option3", "Hindi"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="year_established",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
