# Generated by Django 4.1 on 2023-07-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0016_alter_school_profiles_coed_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school_profiles",
            name="about",
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="cover",
            field=models.ImageField(
                default="static\\images\\school_default_cover1.jpg",
                null=True,
                upload_to="school_covers",
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="logo",
            field=models.ImageField(
                default="static\\images\\school_default_2.png",
                null=True,
                upload_to="school_logos",
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="school_format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.schoolformat",
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="school_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.schooltype",
            ),
        ),
    ]
