# Generated by Django 4.1 on 2023-07-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0017_alter_school_profiles_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolboard",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
