# Generated by Django 4.1 on 2023-07-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0018_schoolboard_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolformat",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schooltype",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
