# Generated by Django 4.1 on 2023-07-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0019_schoolformat_slug_schooltype_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="school_profiles",
            options={
                "verbose_name": "School Profile",
                "verbose_name_plural": "School Profiles",
            },
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="coed_status",
            field=models.CharField(
                blank=True,
                choices=[("1", "Co-ed"), ("2", "Boys"), ("3", "Girls")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="ownership",
            field=models.CharField(
                blank=True,
                choices=[("1", "Private"), ("2", "Government")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="school_medium",
            field=models.CharField(
                blank=True,
                choices=[("1", "English"), ("2", "Bengali"), ("3", "Hindi")],
                max_length=10,
                null=True,
            ),
        ),
    ]
