# Generated by Django 4.1 on 2023-07-10 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Profiles", "0020_alter_school_profiles_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school_profiles",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
