# Generated by Django 4.1 on 2023-07-14 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Profiles", "0021_alter_school_profiles_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school_profiles",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
