# Generated by Django 4.1 on 2023-07-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0023_school_profiles_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AC_Classes",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Wifi",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Smart_Classes",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Boys_Hostel",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Girls_Hostel",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Cafeteria",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Library",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Playground",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Auditorium",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "CCTV",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "GPS_Bus_Tracking_App",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Student_Tracking_App",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Alumni_Association",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Medical_Room",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Day_care",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Meals",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Transportation",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Art_and_Craft",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Dance",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Drama",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Music",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Picnics_and_excursion",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Debate",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Gardening",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Indoor_Sports",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Outdoor_Sports",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Karate",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Taekwondo",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Yoga",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Gym",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Swimming_Pool",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Skating",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Horse_Riding",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Computer_Lab",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Science_Lab",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Robotics_Lab",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Ramps",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Washrooms",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "Elevators",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO"), ("U", "Unknown")],
                        default="U",
                        max_length=10,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="Profiles.school_profiles",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "School Facilities",
            },
        ),
    ]
