# Generated by Django 4.1 on 2023-07-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0024_schoolfacilities"),
    ]

    operations = [
        migrations.AddField(
            model_name="school_profiles",
            name="latitude",
            field=models.CharField(
                blank=True, default="20.5937", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="school_profiles",
            name="longitude",
            field=models.CharField(
                blank=True, default="78.9629", max_length=200, null=True
            ),
        ),
    ]
