# Generated by Django 4.1 on 2023-07-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0025_school_profiles_latitude_school_profiles_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school_profiles",
            name="latitude",
            field=models.CharField(
                blank=True, default="22.960301417322228", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="school_profiles",
            name="longitude",
            field=models.CharField(
                blank=True, default="79.56199782489124", max_length=200, null=True
            ),
        ),
    ]
