# Generated by Django 4.1 on 2023-07-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Profiles", "0023_school_profiles_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionOpenClasses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_limit", models.IntegerField(blank=True, null=True)),
                ("form_price", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "Open"), ("0", "Closed")], max_length=10
                    ),
                ),
                (
                    "class_opened",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Profiles.schoolclass",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="school_profiles",
                        to="Profiles.school_profiles",
                    ),
                ),
            ],
        ),
    ]
