# Generated by Django 4.1 on 2023-07-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Parent", "0006_alter_parentprofile_options_childprofile"),
        ("Profiles", "0023_school_profiles_is_featured"),
        ("Admissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionopenclasses",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("1", "Open"), ("0", "Closed")],
                default="0",
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ApplicationForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_name", models.CharField(blank=True, max_length=20, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "mother_toungh",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("religion", models.CharField(blank=True, max_length=20, null=True)),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, max_length=300, null=True)),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Parent.childprofile",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="application_form",
                        to="Parent.parentprofile",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="applications_received",
                        to="Profiles.school_profiles",
                    ),
                ),
                (
                    "submitted_for_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Admissions.admissionopenclasses",
                    ),
                ),
            ],
        ),
    ]
