# Generated by Django 4.1 on 2023-07-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0024_schoolfacilities"),
        ("Admissions", "0002_alter_admissionopenclasses_status_applicationform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admissionopenclasses",
            options={"verbose_name_plural": "Admission Open Classes"},
        ),
        migrations.AlterModelOptions(
            name="applicationform",
            options={"verbose_name_plural": "Application Form"},
        ),
        migrations.AlterField(
            model_name="applicationform",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applicationform",
            name="school",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="applications_received",
                to="Profiles.school_profiles",
            ),
        ),
    ]
