# Generated by Django 4.1 on 2023-07-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Admissions", "0003_alter_admissionopenclasses_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationform",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
