# Generated by Django 4.1 on 2023-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Admissions", "0004_applicationform_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationform",
            name="is_paid",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
