# Generated by Django 4.1 on 2023-06-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=models.EmailField(
                    max_length=200, unique=True, verbose_name="email_address"
                ),
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
