# Generated by Django 4.1 on 2023-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "A User with that email already exists."},
                max_length=200,
                verbose_name="email Address",
            ),
        ),
    ]
