# Generated by Django 4.1 on 2023-07-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0021_alter_school_profiles_user"),
        ("Parent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentprofile",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.city",
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.country",
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="income_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("70000", "Below 70,000"),
                    ("140000", "70,000 to 1.4 Lakhs"),
                    ("240000", "1.4 Lakhs to 2.4 Lakhs"),
                    ("800000", "2.4 Lakhs to 8 Lakhs"),
                    ("1500000", "8 Lakhs to 15 Lakhs"),
                    ("3000000", "15 Lakhs to 30 Lakhs"),
                    ("15000000", "30 Lakhs to 1.5 Crores"),
                    ("99999999", "Above 1.5 Crores"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="interested_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.schoolclass",
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("No", "No Formal Education"),
                    ("12", "Class 12 or below"),
                    ("Graduate", "Graduate"),
                    ("Post Graduate", "Post Graduate"),
                    ("Doctorate", "Doctorate"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="relation_with_child",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Father", "Father"),
                    ("Mother", "Mother"),
                    ("Guardian", "Guardian"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parentprofile",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.state",
            ),
        ),
    ]
