# Generated by Django 4.1 on 2023-07-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0022_alter_school_profiles_user"),
        ("Parent", "0003_alter_parentprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentprofile",
            name="interested_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Profiles.schoolclass",
            ),
        ),
    ]
