# Generated by Django 4.1 on 2023-07-14 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Parent", "0004_alter_parentprofile_interested_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parentprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
