# Generated by Django 4.1 on 2023-07-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Profiles", "0023_school_profiles_is_featured"),
        ("Parent", "0005_alter_parentprofile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parentprofile",
            options={"verbose_name_plural": "Parent Profile"},
        ),
        migrations.CreateModel(
            name="ChildProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("B", "Boy"), ("G", "Girl")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "interested_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Profiles.schoolclass",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="Parent.parentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Child Profile",
            },
        ),
    ]
