# Generated by Django 4.1 on 2023-07-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Parent", "0006_alter_parentprofile_options_childprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Boy", "Boy"), ("Girl", "Girl")],
                max_length=10,
                null=True,
            ),
        ),
    ]
